### ISSUE TITLE
Doesn't decompile the .appex files, for example in a vpn

### ISSUE THREAD

**Issue by Taherismail17** [Sacmunraga/sacmunCrack#1]

**Comment by Sacmunraga** [comment]
Which VPN?

**Comment by Taherismail17** [comment]
https://www.sslproxies.org

Can you add a option to connect to HTTP proxy? I can parse website

**Comment by Taherismail17** [comment]
https://free-ss.site

**Comment by Sacmunraga** [comment]
I believe you are mistaken. This is a script to decrypt iOS applications and I have no clue what your attempting to explain.

**Comment by Taherismail17** [comment]
Sorry, had the wrong thread. When decompiling the app it worked perfectly fine but all extensions of the app do not work inside of Hopper. The app does

**Comment by Sacmunraga** [comment]
It better to put this issue on https://github.com/BishopFox/bfinject or https://github.com/BishopFox/bfdecrypt, because my branch is made more to improve convenience, and I did not touch any of the code from the libraries...
